# Shell variables
# Generated by 'wal'
wallpaper="/home/svl10/Downloads/r1999.jpg"

# Special
background='#040403'
foreground='#c0c0c0'
cursor='#c0c0c0'

# Colors
color0='#040403'
color1='#4F4737'
color2='#675336'
color3='#606152'
color4='#916E4C'
color5='#78876A'
color6='#9C946D'
color7='#c0c0c0'
color8='#424242'
color9='#4F4737'
color10='#675336'
color11='#606152'
color12='#916E4C'
color13='#78876A'
color14='#9C946D'
color15='#c0c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
