--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/svl10/Downloads/r1999.jpg"

-- Special
background="#040403"
foreground="#c0c0c0"
cursor="#c0c0c0"

-- Colors
color0="#040403"
color1="#4F4737"
color2="#675336"
color3="#606152"
color4="#916E4C"
color5="#78876A"
color6="#9C946D"
color7="#c0c0c0"
color8="#424242"
color9="#4F4737"
color10="#675336"
color11="#606152"
color12="#916E4C"
color13="#78876A"
color14="#9C946D"
color15="#c0c0c0"
